apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-nodejs
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85